# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171122_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecash',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ecash',
        ),
        migrations.DeleteModel(
            name='fund',
        ),
    ]
