# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20171122_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='annuity',
            field=models.CharField(default='100', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dollar_balance',
            field=models.CharField(default='100', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hk_balance',
            field=models.CharField(default='100', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='yuan_balance',
            field=models.CharField(default='100', max_length=200),
        ),
    ]
