# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20171122_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up',
            name='annuity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='up',
            name='dollar_balance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='up',
            name='hk_balance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='up',
            name='yuan_balance',
            field=models.IntegerField(default=100),
        ),
    ]
