# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_ecash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecash',
            name='e_balance',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
